language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev --deploy
script:
  - ./scripts/get_maxmind.sh
  - python manage.py test
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv