# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0010_auto_20160129_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('details_url', models.URLField()),
                ('artists', models.ManyToManyField(related_name='releases', to='concertowl.Artist')),
            ],
        ),
    ]
