# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('concertowl', '0011_release'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Release',
            new_name='Record',
        ),
    ]
