# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertowl', '0012_auto_20160630_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
